import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Blink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html>
        <body>
        
      {children}
        </body>
      </html>

  );
}
